# Generated by Django 2.2 on 2020-08-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(default='active', max_length=25),
            preserve_default=False,
        ),
    ]
